### ISSUE TITLE
Documentation for creating initial MCM script is wrong

### ISSUE THREAD

**Issue by Glanzer-modder** [Exit-9B/MCM-Helper#14]
I think [the documentation for creating an initial config script](https://github.com/Exit-9B/MCM-Helper/wiki/Creating-a-Config-Script) is wrong. Instead of this:

Scriptname MyConfigMenu extends MCM_ConfigBase

Shouldn't it say this?

Scriptname MyConfigMenu extends SKI_ConfigBase

**Comment by Osmosis-Wrench** [comment]
It would be extending SKI_ConfigBase if it was a normal MCM. 
To use MCM Helper it needs to be extending MCM_ConfigBase.

[If you look at the code](https://github.com/Exit-9B/MCM-Helper/blob/a71ca41f07b8e3715e4ac74f19309ea9c48a2d36/dist/Detail/Source/Scripts/MCM_ConfigBase.psc#L1) you can see that MCM_ConfigBase extends SKI_ConfigBase, so default MCM functions are avalible while also giving access to the extra functions that MCM Helper provides.

**Comment by Glanzer-modder** [comment]
Ok, thanks for the clarification!
